=== Kseniya-hash/Epam-task-5/Epam Task5 deadline 09.09/src/resources/gemSchema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" 
	targetNamespace="http://www.gemstask.org/gemSchema" 
	xmlns:tns="http://www.gemstask.org/gemSchema" 
	elementFormDefault="qualified">
	<element name="gems">
		<complexType>
			<sequence>
				<element name ="gem" type="tns:gem" minOccurs="1" maxOccurs="unbounded"/>
			</sequence>
		</complexType>
	</element>
	
	<complexType name="gem">
		<sequence>
			<element name="name" type="string"/>
			<element name ="visualParameters" type="tns:visualParameters"/>
		</sequence>
		<attribute name="id" type="ID" use="required"/>
		<attribute name ="preciousness" type="tns:preciousness" default="semiprecious"/>
		<attribute name="origin" type="string" use="optional"/>
		<attribute name="originDate" type="date" use="optional"/>
	</complexType>
	
	<simpleType name="preciousness">
		<restriction base="string">
			<enumeration value="precious"></enumeration>
			<enumeration value="semiprecious"></enumeration>
		</restriction>
	</simpleType>
	
	<complexType name="visualParameters">
		<sequence>
			<element name="color" type="string"/>
			<element name="transparency" type="tns:transparency"/>
			<element name="edgeNumber" type="tns:edgeNumber"/>
			<element name="value" type="tns:positiveDouble"/>
		</sequence>
	</complexType>
	
	<simpleType name="transparency">
		<restriction base="double">
			<minInclusive value="0"/>
			<maxInclusive value="100"/>
		</restriction>
	</simpleType>
	
	<simpleType name="edgeNumber">
		<restriction base="int">
			<minInclusive value="4"/>
			<maxInclusive value="15"/>
		</restriction>
	</simpleType>
	
	<simpleType name="positiveDouble">
    	<restriction base="double">
      		<minExclusive value="0"/>
    	</restriction>
	</simpleType>
</schema>

=== Kseniya-hash/Epam-task-5/Epam Task5 deadline 09.09/src/resources/gems.xml
<?xml version="1.0" encoding="UTF-8"?>
<gems xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
		xmlns="http://www.gemstask.org/gemSchema"
		xsi:schemaLocation="http://www.gemstask.org/gemSchema gemSchema.xsd">
		
	<gem id="ID-1" originDate="2000-09-23" preciousness="precious">
		<name>Брилиант</name>
		<visualParameters>
			<color>голубой</color>
			<transparency>0</transparency>
		 	<edgeNumber>10</edgeNumber>
		 	<value>3</value>
		</visualParameters>
	</gem>
	
	<gem id="ID-2" preciousness="precious">
		<name>Брилиант</name>
		<visualParameters>
			<color>голубой</color>
			<transparency>20</transparency>
		 	<edgeNumber>15</edgeNumber>
		 	<value>1.5</value>
		</visualParameters>
	</gem>
	
	<gem id="ID-3" origin="Колумбия" originDate="2015-09-23" preciousness="precious">
		<name>Изумруд</name>
		<visualParameters>
			<color>зеленый</color>
			<transparency>80</transparency>
		 	<edgeNumber>5</edgeNumber>
		 	<value>10</value>
		</visualParameters>
	</gem>
	
	<gem id="ID-4" originDate="2011-03-11" preciousness="precious">
		<name>Рубин</name>
		<visualParameters>
			<color>красный</color>
			<transparency>0</transparency>
		 	<edgeNumber>16</edgeNumber>
		 	<value>3</value>
		</visualParameters>
	</gem>
	
	<gem id="ID-5" origin="США" originDate="2000-09-23" preciousness="precious">
		<name>Сапфир</name>
		<visualParameters>
			<color>синий</color>
			<transparency>50</transparency>
		 	<edgeNumber>12</edgeNumber>
		 	<value>7.5</value>
		</visualParameters>
	</gem>
	
	<gem id="ID-6">
		<name>Аметист</name>
		<visualParameters>
			<color>фиолетовый</color>
			<transparency>90</transparency>
		 	<edgeNumber>5</edgeNumber>
		 	<value>4.5</value>
		</visualParameters>
	</gem>
	
	<gem id="ID-7" preciousness="semiprecious">
		<name>Аквамарин</name>
		<visualParameters>
			<color>голубой</color>
			<transparency>0</transparency>
		 	<edgeNumber>0</edgeNumber>
		 	<value>6</value>
		</visualParameters>
	</gem>
	
	<gem id="ID-8" origin="Индия" preciousness="precious">
		<name>Сапфир</name>
		<visualParameters>
			<color>синий</color>
			<transparency>30</transparency>
		 	<edgeNumber>8</edgeNumber>
		 	<value>10</value>
		</visualParameters>
	</gem>
	
	<gem id="ID-9" originDate="2010-10-16" preciousness="semiprecious">
		<name>Агат</name>
		<visualParameters>
			<color>розовый</color>
			<transparency>100</transparency>
		 	<edgeNumber>15</edgeNumber>
		 	<value>4</value>
		</visualParameters>
	</gem>
	
	<gem id="ID-10" preciousness="precious">
		<name>Рубин</name>
		<visualParameters>
			<color>красный</color>
			<transparency>10</transparency>
		 	<edgeNumber>15</edgeNumber>
		 	<value>3</value>
		</visualParameters>
	</gem>
	
	<gem id="ID-11">
		<name>Топаз</name>
		<visualParameters>
			<color>голубой</color>
			<transparency>20</transparency>
		 	<edgeNumber>10</edgeNumber>
		 	<value>6</value>
		</visualParameters>
	</gem>
	
	<gem id="ID-12" origin="Бразилия" preciousness="precious">
		<name>Изумруд</name>
		<visualParameters>
			<color>зеленый</color>
			<transparency>70</transparency>
		 	<edgeNumber>15</edgeNumber>
		 	<value>13</value>
		</visualParameters>
	</gem>
	
	<gem id="ID-13" preciousness="precious">
		<name>Брилиант</name>
		<visualParameters>
			<color>желтый</color>
			<transparency>10</transparency>
		 	<edgeNumber>15</edgeNumber>
		 	<value>10</value>
		</visualParameters>
	</gem>
	
	<gem id="ID-14" origin="Индия" preciousness="semiprecious">
		<name>Гранат</name>
		<visualParameters>
			<color>бордовый</color>
			<transparency>40</transparency>
		 	<edgeNumber>8</edgeNumber>
		 	<value>10</value>
		</visualParameters>
	</gem>
	
	<gem id="ID-15" preciousness="semiprecious">
		<name>Хризолин</name>
		<visualParameters>
			<color>зеленый</color>
			<transparency>70</transparency>
		 	<edgeNumber>12</edgeNumber>
		 	<value>15</value>
		</visualParameters>
	</gem>
	
	<gem id="ID-16" preciousness="semiprecious">
		<name>Топаз</name>
		<visualParameters>
			<color>голубой</color>
			<transparency>20</transparency>
		 	<edgeNumber>15</edgeNumber>
		 	<value>20</value>
		</visualParameters>
	</gem>
</gems>

=== Kseniya-hash/Epam-task-5/Epam Task5 deadline 09.09/test/resources/testInvalidXML.xml
<?xml version="1.0" encoding="UTF-8"?>
<gems xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
		xmlns="http://www.gemstask.org/gemSchema"
		xsi:schemaLocation="http://www.gemstask.org/gemSchema gemSchema.xsd">
		
	<gem id="ID-1" preciousness="precious">
		<name>Рубин</name>
		<visualParameters>
			<color>красный</color>
			<transparency>0</transparency>
		 	<edgeNumber>10</edgeNumber>
		 	<value>3</value>
		</visualParameters>
	</gem>

=== Kseniya-hash/Epam-task-5/Epam Task5 deadline 09.09/test/resources/testAllGemsValid.xml
<?xml version="1.0" encoding="UTF-8"?>
<gems xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
		xmlns="http://www.gemstask.org/gemSchema"
		xsi:schemaLocation="http://www.gemstask.org/gemSchema gemSchema.xsd">
		
	<gem id="ID-1" preciousness="precious">
		<name>Рубин</name>
		<visualParameters>
			<color>красный</color>
			<transparency>0</transparency>
		 	<edgeNumber>10</edgeNumber>
		 	<value>3</value>
		</visualParameters>
	</gem>
	
	<gem id="ID-2" preciousness="precious">
		<name>Брилиант</name>
		<visualParameters>
			<color>голубой</color>
			<transparency>20</transparency>
		 	<edgeNumber>15</edgeNumber>
		 	<value>1.5</value>
		</visualParameters>
	</gem>
	
	<gem id="ID-3" origin="Колумбия" originDate="2015-09-23" preciousness="precious">
		<name>Изумруд</name>
		<visualParameters>
			<color>зеленый</color>
			<transparency>80</transparency>
		 	<edgeNumber>5</edgeNumber>
		 	<value>10</value>
		</visualParameters>
	</gem>
	
	<gem id="ID-6">
		<name>Аметист</name>
		<visualParameters>
			<color>фиолетовый</color>
			<transparency>90</transparency>
		 	<edgeNumber>5</edgeNumber>
		 	<value>4.5</value>
		</visualParameters>
	</gem>
</gems>
